# Generated by Django 2.1.2 on 2018-12-08 06:08

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models.fields.bit


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_nurserybookmark_nurserydefaulttoursetting_nurseryscore_nurserytours_usernurserymapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryReservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=255, null=True)),
                ('is_active', django_mysql.models.fields.bit.Bit1BooleanField(default=True)),
                ('status', models.IntegerField(default=0)),
                ('reservation_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nursery_reservations',
                'managed': False,
            },
        ),
    ]
