# Generated by Django 2.1.2 on 2018-12-08 07:51

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models.fields.bit


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_nurseryreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryTour',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('special_start_time', models.TimeField(default=None)),
                ('special_end_time', models.TimeField(default=None)),
                ('special_capacity', models.TimeField(default=None)),
                ('special_note', models.CharField(default=None, max_length=255)),
                ('is_active', django_mysql.models.fields.bit.Bit1BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nursery_tours',
                'managed': False,
            },
        ),
    ]
