NURSERY_FREE_NUM_FMT = 'nursery_id:{}age_id:{}'

NOT_ONE_AGE_ID = 1
ONE_YEAR_OLD_AGE_ID = 2
TWO_YEAR_OLD_AGE_ID = 3
THREE_YEAR_OLD_AGE_ID = 4
FOUR_YEAR_OLD_AGE_ID = 5
EXTENT_AGE_ID = 6
OTHER_AGE_ID = 7

AGE_IDS = [NOT_ONE_AGE_ID, ONE_YEAR_OLD_AGE_ID, TWO_YEAR_OLD_AGE_ID, THREE_YEAR_OLD_AGE_ID, FOUR_YEAR_OLD_AGE_ID,
           EXTENT_AGE_ID]
